### ISSUE TITLE
Callback not triggering?

### ISSUE THREAD

**Issue by SachaG** [MiroHibler/meteor-mailchimp#19]
For some reason, my callbacks on `api.call()` are not triggering at all, even though the API call seems to be succeeding. Any idea why that might be happening?

**Comment by SachaG** [comment]
I'm not super clear on the wrapAsync stuff, but maybe the [last commit](https://github.com/MiroHibler/meteor-mailchimp/commit/79a8ec48a2621756334bd6bae19a0a70a3b2f2d6#diff-72e6188d62035740a964843d1dc45caeR41) disabled the callbacks somehow? Is that possible?

**Comment by SachaG** [comment]
I made a reproduction here: 

http://meteorpad.com/pad/8NnXmWF3gobfaN4ug/MailChimp%20test

Just open the app in a new window (http://app-saflr2js.meteorpad.com/) and call `Meteor.call('testMailChimp', 'your-api-key', 'your-list-id')`

The callback doesn't fire as far as I can tell.

**Comment by themeteorchef** [comment]
Running into the same issue with callbacks not firing as well. Tried a few different implementations but not getting anything back (i.e. no errors or result being returned).

**Comment by SachaG** [comment]
Oh, apparently the docs are just outdated, you shouldn't use the callback anymore. Thanks @dburles :)

http://meteorpad.com/pad/EBczK4RWeLyEMyCsX/Copy%20of%20MailChimp%20test

**Comment by themeteorchef** [comment]
@SachaG that'll do it :) Thanks!

**Comment by MiroHibler** [comment]
@SachaG, wasn't it you who [asked for](https://github.com/MiroHibler/meteor-mailchimp/issues/8) the wrapAsync behaviour? :-P

Anyways, thank you for pointing it out - it's my fault, I unintentionally forgot to (re)implement callback.

And yes - the docs are outdated as well :(

Too many things to do and so little time...

I'm gonna fix that, stay tuned.

**Comment by dburles** [comment]
Hey the callback isn't required anymore since you're using wrapAsync.

**Comment by SachaG** [comment]
@MiroHibler yes, and it's very much appreciated! I agree we don't need the callback anymore, I was just confused by the documentation :)

**Comment by MiroHibler** [comment]
@SachaG, I was just kidding ;)

BTW, thank you for the reproduction code.

I have to admit that I'm still trying to wrap my head around the `wrapAsync`, so I'll be checking [certain blog](https://www.discovermeteor.com/blog/wrapping-npm-packages/) soon ;)

**Comment by SachaG** [comment]
I'm ashamed, but since writing that blog post I kinda forgot most of that
stuff too…

**Comment by MiroHibler** [comment]
I hear ya! :)

With things being so dynamic it happens to me more often than I'm willing to admit ;)

Not to mention going back to check my own old code... like I've never seen it before...

But that's what docs (and code comments) are for, right? ;)

**Comment by MiroHibler** [comment]
Alright, I reinstated server-side callback in case someone still wants to use it instead of Meteor.wrapAsync method :P

**Comment by MiroHibler** [comment]
Oh, and docs are updated too ;)

BTW, check also these wrappers:

 * [MailChimp Lists](https://github.com/MiroHibler/meteor-mailchimp-lists)
 * [MailChimp Campaigns](https://github.com/MiroHibler/meteor-mailchimp-campaigns)

**Comment by SachaG** [comment]
Oh, very cool!

**Comment by MiroHibler** [comment]
I'm trying to set up a demo for you on Meteorpad but it pulls the old version (v1.0.3) of miro:mailchimp and the other two are not even visible yet, so maybe some other time/day...
