### ISSUE TITLE
Error: No API Key Defined

### ISSUE THREAD

**Issue by aspiringpro** [MiroHibler/meteor-mailchimp#20]
Where do I put the settings.json file?  I have it in a server folder... I ran meteor --settings settings.json and still no success.

**Comment by MiroHibler** [comment]
If you're starting your app with:

```sh
meteor --settings settings.json
```

then you should put it in a root of your app. Otherwise, add the proper path, for example:

```sh
meteor --settings server/settings.json
// or
meteor --settings wherever/you/put/it/settings.json
```
