### ISSUE TITLE
Can we customize the template's CSS?

### ISSUE THREAD

**Issue by sdybskiy** [MiroHibler/meteor-mailchimp#21]
is there a way to be able to target elements within the template so we can customize them?

**Comment by MiroHibler** [comment]
Sure! There's no CSS in the package and you're free to set your own.

Take a look at [bundled template](https://github.com/MiroHibler/meteor-mailchimp/blob/master/lib/client/views/subscribe/subscribe.html) for classes and define them in your own CSS as you wish.

**Comment by sdybskiy** [comment]
that means I have to have the package cloned locally right?

**Comment by sdybskiy** [comment]
Thanks, figured it out :)
