### ISSUE TITLE
Multiple {{> MailChimpListSubscribe}} in one window

### ISSUE THREAD

**Issue by sergical** [MiroHibler/meteor-mailchimp#23]
I have the `{{> MailChimpListSubscribe}}` in a modal as well as on the page, and the modal one doesn't seem to work. Am I able to have more than one in a single rendered window?

**Comment by MiroHibler** [comment]
Could you provide some code for testing?

**Comment by a8h1nay** [comment]
Same issue here. Want to use two subscription forms on single page. One doesn't work :(

**Comment by MiroHibler** [comment]
Are you using the same API key, but different mailing list IDs?
