### ISSUE TITLE
Example Code Returns No Campaigns

### ISSUE THREAD

**Issue by digilord** [MiroHibler/meteor-mailchimp#25]
I am using your example code to make sure that MailChimp is setup correctly. I am getting back the following from Meteor:

```
I20150225-17:18:30.937(-7)? [MailChimp][Campaigns][List]:  { total: 0, data: [], errors: [] }
```

My API key works for adding subscribers, just not for using the `.call` method. Is there an issue with the code in the examples?

**Comment by MiroHibler** [comment]
So, what was the problem?

**Comment by digilord** [comment]
I was thinking that lists were part of campaigns. So I saw four lists in my interface, but the API was returning zero. I was very confused. Then I read more of the API. (lightbulb) I understood how things worked after that. Sorry to have created an issue for this. I had to RTFM a little more.

Cheers!

**Comment by MiroHibler** [comment]
No worries, it happens to me more times than I'm willing to admit ;)
