### ISSUE TITLE
Any way to avoid including API key in code?

### ISSUE THREAD

**Issue by davidrea** [MiroHibler/meteor-mailchimp#28]
My app is both deployed and open-sourced, so even though my calls into the mailchimp API are on the server side, I'd need to avoid ever committing a version of code that contains my API keys.

Since the API key is included in settings.json (which can be excluded from version control) is there any way to utilize this copy of the key rather than require it in code? Thanks...

**Comment by MiroHibler** [comment]
The possibility to supply your credentials in each call to the API (serverside/clentside) is there for convenience - for example if you want to access multiple mailchimp accounts dynamically within your app.

Other than that, tere's no need to provide credentials in each API call whatsoever - the ones from settings.json will be used by default.

**Comment by davidrea** [comment]
Thanks for the quick response. I tried setting the apiKey variable in the constructor call to null, but got an exception ("No API key defined") at app startup. Fixed it by pulling in the API key from the settings:

var mailChimp = new MailChimp( Meteor.settings.private.MailChimp.apiKey, { version: '2.0' } );
