### ISSUE TITLE
Set title argument dosnt seem to work

### ISSUE THREAD

**Issue by molleman** [MiroHibler/meteor-mailchimp#29]
https://github.com/MiroHibler/meteor-mailchimp/commit/8d95cde143083a64f5719c7081b536a8a9c0fdea

The above fix so you can add your own title does not seem to work for me

`{{>MailChimpListSubscribe title='Subscribe for more'}}`

**Comment by MiroHibler** [comment]
I just tested it and it seems to work for me... (sorry for the delay, been ovefully busy...

**Comment by MiroHibler** [comment]
I just tested it and it seems to be working just fine... (sorry for the delay, I've been very busy lately)

**Comment by MiroHibler** [comment]
Hey @molleman, is it still an issue?

**Comment by MiroHibler** [comment]
Closing this one as it doesn't appear to be an issue anymore.
