### ISSUE TITLE
Changes messages

### ISSUE THREAD

**Issue by ColeTownsend** [MiroHibler/meteor-mailchimp#34]
I think there should be a way to change the {{ message }}. It would be really nice for copywriting purposes.

**Comment by ColeTownsend** [comment]
Just went in and manually changed 'em

**Comment by meetmagdalene** [comment]
Where did you find the file to change within a meteor project? I'm on Meteor 1.7.0.3 and the files for this package do not appear to be native in my source code anywhere. ??
